# used for local development
services:
  traefik:
    image: "traefik:v3.2"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - net
    volumes:
      - "letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--experimental.fastProxy"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=lyykfi@gmail.com.ru"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--log.level=DEBUG"
  front:
    container_name: landing
    image: nginx:stable-alpine
    networks:
      - net
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.compress.compress=true"
      - "traefik.http.services.web_desktop_secure.loadbalancer.server.port=80"
      - "traefik.http.routers.web_desktop_secure.tls=true"
      - "traefik.http.routers.web_desktop_secure.entrypoints=websecure"
      - "traefik.http.routers.web_desktop_secure.tls.certresolver=myresolver"
      - "traefik.http.routers.web_desktop_secure.rule=Host(`birthday.oncologica.ru`)"
      - "traefik.http.routers.web_desktop_secure.middlewares=compress"
    build:
      dockerfile: ./Dockerfile
    volumes:
      - "letsencrypt:/letsencrypt"
    ports:
      - "8081:80"

networks:
  net:
    driver: bridge

volumes:
  letsencrypt:
    name: letsencrypt